#############################################################################
# Generated by PAGE version 4.22
#  in conjunction with Tcl version 8.6
#  May 06, 2019 05:30:04 PM -0300  platform: Windows NT
set vTcl(timestamp) ""


if {!$vTcl(borrow)} {

set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}

# vTcl Code to Load User Fonts

vTcl:font:add_font \
    "-family {Segoe UI} -size 14 -weight bold -slant italic -underline 0 -overstrike 0" \
    user \
    vTcl:font11
#################################
#LIBRARY PROCEDURES
#


if {[info exists vTcl(sourcing)]} {

proc vTcl:project:info {} {
    set base .top42
    global vTcl
    set base $vTcl(btop)
    if {$base == ""} {
        set base .top42
    }
    namespace eval ::widgets::$base {
        set dflt,origin 0
        set runvisible 1
    }
    namespace eval ::widgets_bindings {
        set tagslist _TopLevel
    }
    namespace eval ::vTcl::modules::main {
        set procs {
        }
        set compounds {
        }
        set projectType single
    }
}
}

#################################
# GENERATED GUI PROCEDURES
#

proc vTclWindow.top42 {base} {
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -background {#d9d9d9} -highlightbackground {#d9d9d9} \
        -highlightcolor black 
    wm focusmodel $top passive
    wm geometry $top 345x380+400+200
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1370 749
    wm minsize $top 120 1
    wm overrideredirect $top 0
    wm resizable $top 0 0
    wm deiconify $top
    wm title $top "Sistema de Inspeção Visual"
    vTcl:DefineAlias "$top" "Main" vTcl:Toplevel:WidgetProc "" 1
    frame $top.fra46 \
        -borderwidth 2 -relief groove -background {#b5dcdd} \
        -highlightbackground {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.fra46" "Frame1" vTcl:WidgetProc "Main" 1
    set site_3_0 $top.fra46
    button $site_3_0.but47 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#a5c8c9} -command {lambda: exec(open("BAQ.py").read())} \
        -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 15 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Modo Operação} 
    vTcl:DefineAlias "$site_3_0.but47" "ButtonMO" vTcl:WidgetProc "Main" 1
    button $site_3_0.but48 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#a5c8c9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 15 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Modo Treinamento} 
    vTcl:DefineAlias "$site_3_0.but48" "ButtonMA" vTcl:WidgetProc "Main" 1
    button $site_3_0.but49 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#a5c8c9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 15 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text {Modo Aquisição} 
    vTcl:DefineAlias "$site_3_0.but49" "ButtonMT" vTcl:WidgetProc "Main" 1
    label $site_3_0.lab54 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#b5dcdd} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 14 -weight bold -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -text {Sistema de Inspeção Visual} 
    vTcl:DefineAlias "$site_3_0.lab54" "Label2" vTcl:WidgetProc "Main" 1
    place $site_3_0.but47 \
        -in $site_3_0 -x 60 -y 60 -width 197 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but48 \
        -in $site_3_0 -x 60 -y 180 -width 197 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.but49 \
        -in $site_3_0 -x 60 -y 120 -width 197 -relwidth 0 -height 44 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $site_3_0.lab54 \
        -in $site_3_0 -x 8 -y 10 -width 309 -relwidth 0 -height 33 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra44 \
        -borderwidth 2 -relief groove -background {#b5dcdd} \
        -highlightbackground {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.fra44" "Frame4" vTcl:WidgetProc "Main" 1
    set site_3_0 $top.fra44
    label $site_3_0.lab46 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#b5dcdd} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 9} -foreground {#000000} \
        -highlightbackground {#d9d9d9} -highlightcolor black \
        -text {Ivan Luiz de Oliveira - UNESP Sorocaba - 2019} 
    place $site_3_0.lab46 \
        -in $site_3_0 -x 14 -y 13 -width 296 -relwidth 0 -height 23 \
        -relheight 0 -anchor nw -bordermode ignore 
    frame $top.fra43 \
        -borderwidth 2 -relief groove -background {#b5dcdd} \
        -highlightbackground {#d9d9d9} -highlightcolor black 
    vTcl:DefineAlias "$top.fra43" "Frame3" vTcl:WidgetProc "Main" 1
    set site_3_0 $top.fra43
    button $site_3_0.but44 \
        -activebackground {#f9f9f9} -activeforeground black \
        -background {#a5c8c9} -disabledforeground {#a3a3a3} \
        -font {-family {Segoe UI} -size 15 -slant italic} \
        -foreground {#000000} -highlightbackground {#d9d9d9} \
        -highlightcolor black -pady 0 -text Configurações 
    vTcl:DefineAlias "$site_3_0.but44" "ButtonCFG" vTcl:WidgetProc "Main" 1
    place $site_3_0.but44 \
        -in $site_3_0 -x 60 -y 20 -width 197 -height 44 -anchor nw \
        -bordermode ignore 
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.fra46 \
        -in $top -x 10 -y 10 -width 325 -relwidth 0 -height 245 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra44 \
        -in $top -x 10 -y 330 -width 325 -relwidth 0 -height 45 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.fra43 \
        -in $top -x 10 -y 250 -width 325 -relwidth 0 -height 85 -relheight 0 \
        -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

